### ISSUE TITLE
Schedule for backend

### ISSUE THREAD

**Issue by GNUp** [CodeChain-io/codechain-exchange#5]
- [ ] submit order #7 
- [x] get order book #8
- [ ] cancel order #9 
- [x] get my order #10
- [ ] get my completed order history #11
- [x] log all request from a client: Use morgan #12
- [ ] order watcher #13 
- [ ] redesign the order matching specification
